define([
    'mystique/Alpha',
    'mystique/Base',
    'mystique/Boolean',
    'mystique/Chain',
    'mystique/CreditCard',
    'mystique/CreditCardExpiry',
    'mystique/Cvv',
    'mystique/Date',
    'mystique/Email',
    'mystique/Equal',
    'mystique/Float',
    'mystique/GreaterThan',
    'mystique/GreaterThanEqual',
    'mystique/HexColor',
    'mystique/Int',
    'mystique/Length',
    'mystique/LessThan',
    'mystique/LessThanEqual',
    'mystique/NotEqual',
    'mystique/NotRequired',
    'mystique/Password',
    'mystique/Regex',
    'mystique/Required',
    'mystique/Result',
    'mystique/Slug',
    'mystique/String'
],
function(
    Alpha,
    Base,
    Boolean,
    Chain,
    CreditCard,
    CreditCardExpiry,
    Cvv,
    Date,
    Email,
    Equal,
    Float,
    GreaterThan,
    GreaterThanEqual,
    HexColor,
    Int,
    Length,
    LessThan,
    LessThanEqual,
    NotEqual,
    NotRequired,
    Password,
    Regex,
    Required,
    Result,
    Slug,
    String
){
    // module:
    //		mystique/mystique

    mystique = {
        Alpha: Alpha,
        Base: Base,
        Boolean: Boolean,
        Chain: Chain,
        CreditCard: CreditCard,
        CreditCardExpiry: CreditCardExpiry,
        Cvv: Cvv,
        Date: Date,
        Email: Email,
        Equal: Equal,
        Float: Float,
        GreaterThan: GreaterThan,
        GreaterThanEqual: GreaterThanEqual,
        HexColor: HexColor,
        Int: Int,
        Length: Length,
        LessThan: LessThan,
        LessThanEqual: LessThanEqual,
        NotEqual: NotEqual,
        NotRequired: NotRequired,
        Password: Password,
        Regex: Regex,
        Required: Required,
        Result: Result,
        Slug: Slug,
        String: String
    }
});
require(['mystique/mystique'], function(){});
